# Generated by Django 6.0.4 on 2026-04-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.TextField(default="Admin", verbose_name="Автор статті"),
        ),
    ]
